name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          pr_title="${{ github.event.pull_request.title }}"
            echo "PR Title: $pr_title"
          if [[ ! "$pr_title" =~ ^\[(?i)(patch|minor|major)\] ]]; then
            echo "PR title must start with '[Major]', '[Minor]', or '[Patch]'"
            exit 1
          fi