name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^\[(?i)[patch]|[minor]|[major])\]: ]]; then
            echo "PR title must start with '[Major]', '[Minor]', or '[Patch]'"
            exit 1
          fi