name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          if [[ ! ${{ github.event.pull_request.title }} =~ ^(fix|feat|perf): ]]; then
            echo "PR title must start with 'fix:', 'feat:', or 'perf:'"
            exit 1
          fi