name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^([patch]|[minor]|[major]): ]]; then
            echo "PR title must start with '[patch]:', '[minor]:', or '[major]:'"
            exit 1
          fi